# Mathematical functions

### universal function

#### 

#### np.add()

In [2]:
import numpy as geek
in_num1 = 100
in_num2 = 155

print ("1st Input number : ", in_num1)
print ("2nd Input number : ", in_num2)

out_num = geek.add(in_num1, in_num2) 
print ("output number after addition : ", out_num)


1st Input number :  100
2nd Input number :  155
output number after addition :  255


#### np.subtract()

In [4]:

import numpy as geek
in_num1 = 48
in_num2 = 36

print ("1st Input number : ", in_num1)
print ("2nd Input number : ", in_num2)

out_num = geek.subtract(in_num1, in_num2) 
print ("Difference of two input number : ", out_num)

1st Input number :  48
2nd Input number :  36
Difference of two input number :  12


#### np.multiply()

In [6]:
import numpy as geek 
in_num1 = 57
in_num2 = 6

print ("1st Input number : ", in_num1) 
print ("2nd Input number : ", in_num2) 
	
out_num = geek.multiply(in_num1, in_num2) 
print ("output number : ", out_num) 


1st Input number :  57
2nd Input number :  6
output number :  342


 ### Statistical functions

#### np.mean()

In [8]:

import numpy as np 
arr = [200, 62, 77, 1, 34] 

print("arr : ", arr) 
print("mean of arr : ", np.mean(arr)) 



arr :  [200, 62, 77, 1, 34]
mean of arr :  74.8


#### np.median

In [9]:

import numpy as np 
arr = [20, 2, 7, 1, 34] 

print("arr : ", arr) 
print("median of arr : ", np.median(arr)) 



arr :  [20, 2, 7, 1, 34]
median of arr :  7.0


 #### np.std()

In [10]:

import numpy as np 
arr = [[2, 2, 2, 2, 2], 
	[15, 6, 27, 8, 2], 
	[23, 2, 54, 1, 2, ], 
	[11, 44, 34, 7, 2]] 

 
print("\nstd of arr, axis = None : ", np.std(arr)) 
	
print("\nstd of arr, axis = 0 : ", np.std(arr, axis = 0)) 

print("\nstd of arr, axis = 1 : ", np.std(arr, axis = 1)) 



std of arr, axis = None :  15.3668474320532

std of arr, axis = 0 :  [ 7.56224173 17.68473918 18.59267329  3.04138127  0.        ]

std of arr, axis = 1 :  [ 0.          8.7772433  20.53874388 16.40243884]


#### np.var

In [11]:

import numpy as np 
	
# 1D array 
arr = [20, 2, 7, 1, 34] 

print("arr : ", arr) 
print("var of arr : ", np.var(arr)) 

print("\nvar of arr : ", np.var(arr, dtype = np.float32)) 
print("\nvar of arr : ", np.var(arr, dtype = np.float64)) 


arr :  [20, 2, 7, 1, 34]
var of arr :  158.16

var of arr :  158.16

var of arr :  158.16


#### np.min()

In [12]:
import numpy as geek 
in_num1 = 10
in_num2 = 21

print ("Input number1 : ", in_num1) 
print ("Input number2 : ", in_num2) 
	
out_num = geek.minimum(in_num1, in_num2) 
print ("minimum of 10 and 21 : ", out_num) 


Input number1 :  10
Input number2 :  21
minimum of 10 and 21 :  10


#### np.max()

In [13]:
import numpy as geek 
in_num1 = 10
in_num2 = 21

print ("Input number1 : ", in_num1) 
print ("Input number2 : ", in_num2) 
	
out_num = geek.minimum(in_num1, in_num2) 
print ("minimum of 10 and 21 : ", out_num) 


Input number1 :  10
Input number2 :  21
minimum of 10 and 21 :  10


### Linear Algebra Functions

#### np.dot()

In [14]:

import numpy as geek

product = geek.dot(5, 4)
print("Dot Product of scalar values : ", product)

vector_a = 2 + 3j
vector_b = 4 + 5j

product = geek.dot(vector_a, vector_b)
print("Dot Product : ", product)


Dot Product of scalar values :  20
Dot Product :  (-7+22j)


#### np.matmul

In [1]:
import numpy.matlib 
import numpy as np 

a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print (np.matmul(a,b))


[[4 1]
 [2 2]]


#### np.linalg.inv()

In [1]:

import numpy as np
 
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 

print("Rank of A:", np.linalg.matrix_rank(A))
 
print("\nTrace of A:", np.trace(A))
 
print("\nDeterminant of A:", np.linalg.det(A)) # np.linalg.det
 
print("\nInverse of A:\n", np.linalg.inv(A)) # np.linalg.inv
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


#### np.linalg.eig()

In [2]:
import numpy as np 


mat = np.mat("1 -2;1 3")  
print(mat) 
print("") 
evalue, evect = np.linalg.eig(mat)  
print(evalue) 
print("") 
print(evect) 


[[ 1 -2]
 [ 1  3]]

[2.+1.j 2.-1.j]

[[ 0.81649658+0.j          0.81649658-0.j        ]
 [-0.40824829-0.40824829j -0.40824829+0.40824829j]]
