#Arrays in NumPy

In [ ]:
ndarray refers to a multi-dimensional array object within the NumPy library in Python

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(arr[3]) #indexing
print(arr[1:3]) #slicing
print(type(arr))

[1 2 3 4 5]
4
[2 3]
<class 'numpy.ndarray'>


Creating arrays using np.array()

Creating arrays using np.array(), np.zeros(), np.ones(), np.arange(), and np.linspace().

In [14]:
import numpy as np 

my_0D_array=np.array(32)
print(my_0D_array)
my_1D_array = np.array([1, 2, 3, 4, 5])  # Creating a 1-dimensional array

print(my_1D_array) 
print(arr[3]) #indexing
print(arr[1:3]) #slicing


my_2D_array = np.array([[1, 2], [3, 4]]) # Creating a 2-dimensional array

print(my_2D_array) 
print(arr[1:3]) #slicing
my_3D_array = np.array([[1, 2], [3, 4],[6,7]]) # Creating a 3-dimensional array
print(arr[1:3]) #slicing
print(my_3D_array) 

32
[1 2 3 4 5]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [6 7]]


In [ ]:
Creating arrays using  np.zeros()

In [60]:
import numpy as np 
arr=np.zeros(10)
print(arr)
print(arr[3]) #indexing
print(arr[1:3]) #slicing
arr[2]=2
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0.]
[0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]


In [62]:
import numpy as np 
arr=np.ones(10)

print(arr)

arr[2]=2
print(arr)
print(arr[3]) #indexing
print(arr[1:3]) #slicing

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 2. 1. 1. 1. 1. 1. 1. 1.]
[1. 2.]


In [3]:
import numpy as np 

arr= np.arange(5 , 100)
print(arr)

arr= np.arange(5 , 100,3)
print(arr[3]) #indexing
print(arr)


[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52
 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
14
[ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74
 77 80 83 86 89 92 95 98]


In [5]:
import numpy as np 

arr= np.linspace(0,5 , 10)
print(arr[3]) #indexing
print(arr)



1.6666666666666667
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
