# Broadcasting

In [7]:

import numpy as np
matrix = np.array([[1, 2], [3, 4]])
vector = np.array([10, 20])
result = matrix * vector
print(result)

[[10 40]
 [30 80]]


In [9]:
import numpy as np
A = np.array([1, 2, 3])
B = 2
result = A + B
print(result)


[3 4 5]


In [10]:
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
B = np.array([10, 20, 30])            # Shape: (3)
result = A + B
print(result)

[[11 22 33]
 [14 25 36]]


In [12]:
A = np.array([1, 2, 3])  # Shape: (3)
B = np.array([4, 5])     # Shape: (2)
result = A + B
print(result)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 