#Mathematical Functions
Universal functions (ufuncs) like np.add(), np.subtract(), np.multiply().

Universal functions (ufuncs)

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])
c=np.add(arr,arr_1)

print(c)

[ 7  9 11 13 15]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])
c=np.subtract(arr_1,arr)

print(c)

[5 5 5 5 5]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])
c=np.multiply(arr_1,arr)

print(c)

[ 6 14 24 36 50]


In [ ]:
np.mean()

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])
c=np.mean(arr_1)
d=np.mean(arr)
print(c)
print(d)

8.0
3.0


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])
c=np.median(arr_1)

print(c)

8.0


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])
c=np.std(arr_1)

print(c)

1.4142135623730951


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])
c=np.var(arr_1)

print(c)

2.0


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])
c=np.max(arr_1)

print(c)

10


In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])
c=np.min(arr_1)

print(c)

6


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])
c=np.min(arr_1)

print(c)

Linear algebra functions

In [30]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)


array([[4, 1],
       [2, 2]])

In [32]:
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [2, 2]])