#Array Shapes and Reshaping

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,0])
print(arr.shape) #shaping 
print("Number of dimensions:", arr.ndim)

arr_1=np.array([[1],[2],[3]])
print(arr_1.shape) #shaping
print("Number of dimensions:", arr_1.ndim)

(6,)
Number of dimensions: 1
(3, 1)
Number of dimensions: 2


In [33]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
# Reshape to a 1D array

flat_arr = arr.reshape(-1)  

print(flat_arr)


arr1 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9],[10,11,12]])
# Reshape to a 2D array

flat_arr = arr1.reshape(-1,2)  
print(flat_arr)



[1 2 3 4 5 6]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [37]:
import  numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=arr.flatten()
print(a)

[1 2 3 4 5 6 7 8 9]


In [45]:
import numpy as np
arr=np.array([[[1,2],[4,5],[7,8]]])
a=arr.transpose()
print(a)

[[[1]
  [4]
  [7]]

 [[2]
  [5]
  [8]]]


Concatenating and splitting arrays

In [61]:
import numpy as np 
  
arr1 = np.array([[2, 4], [6, 8]]) 
arr2 = np.array([[3, 5], [7, 9]]) 
  
g = np.concatenate((arr1, arr2))
print(g)
g = np.concatenate((arr1, arr2),axis=1)
print(g)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]
[[2 4 3 5]
 [6 8 7 9]]


In [63]:
import numpy as np 
  
arr1 = np.array([[2, 4], [6, 8]]) 
arr2 = np.array([[3, 5], [7, 9]]) 
  
g = np.vstack((arr1, arr2))
print(g)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [65]:
import numpy as np

in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [69]:
import numpy as np

# create a 1-D array
array1 = np.array([0, 1, 2, 3,4,5])

# split into two equal length sub-arrays 
subArrays= np.split(array1, 3)

print(subArrays)

[array([0, 1]), array([2, 3]), array([4, 5])]
