 Array Operations
Arithmetic operations on NumPy arrays :addition , subtraction, multiplication, division).

Arithmetic operations on NumPy arrays :addition

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])

print(arr+arr_1)

[ 7  9 11 13 15]


In [ ]:
#Arithmetic operations on NumPy arrays :subtraction

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])

print(arr-arr_1)

[-5 -5 -5 -5 -5]


In [ ]:
#Arithmetic operations on NumPy arrays :multiplication

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,7,8,9,10])

print(arr*arr_1)

[ 6 14 24 36 50]


In [ ]:
#Arithmetic operations on NumPy arrays :division

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_1 = np.array([6,8,12,16,20])

print(arr/arr_1)

[0.16666667 0.25       0.25       0.25       0.25      ]


In [ ]:
Array Operations  Broadcasting (performing operations on arrays of different shapes).

In [37]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5,0])
print(arr.shape) #shaping 

arr_1=np.array([[1],[2],[3]])
print(arr_1.shape) #shaping

(6,)
(3, 1)


In [21]:
import numpy as np
arr1=np.array([[1,3,6]])
arr_2=np.array([[1,4,5],[3,5,6]])
print(arr1+arr_2)

[[ 2  7 11]
 [ 4  8 12]]


In [45]:
import numpy as np
arr1=np.array([[1,3,6,49]])
a=np.sqrt(arr1)
print(a)

[[1.         1.73205081 2.44948974 7.        ]]


In [49]:
import numpy as np
arr1=np.array([[0,3,6,9]])
a=np.sqrt(arr1)
print(a)

[[0.         1.73205081 2.44948974 3.        ]]


In [ ]:
import numpy as np
arr1=np.array([[0,30,60,90]])
a=np.exp(arr1)
print(a)

In [ ]:


import numpy as np
 
in_array = [1, 3, 5]
print ("Input array : ", in_array)
 
out_array = np.exp(in_array)
print ("Output array : ", out_array)