# Array Manipulation

#### indexing and slicing

In [3]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr[1, 2])  
print(arr[1, :])  
print(arr[:, 2])  
print(arr[0:2, 1:3]) 

6
[4 5 6]
[3 6 9]
[[2 3]
 [5 6]]


#### Masking 

In [2]:

arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print(mask) 
print(arr[mask])  # Output: [4 5 6]
arr[arr % 2 == 0] = 0
print(arr)  # Output: [1 0 3 0 5 0]

[False False False  True  True  True]
[4 5 6]
[1 0 3 0 5 0]


 #### Fancy indexing

In [5]:
arr = np.array([10, 20, 30, 40, 50])


indices = [0, 2, 4]
print(arr[indices]) 
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rows = [0, 1, 2]
cols = [2, 0, 1]
print(arr_2d[rows, cols]) 

[10 30 50]
[3 4 8]
